# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Glade2-Widget
version:      0.1
version_from: lib/Glade2//Widget.pm
installdirs:  site
requires:
    POE::Session::GladeXML2:       0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
